# legacy pivnet token for downloading tile
pivnet_token:

# opsman connection info
opsman_domain_or_ip_address:
opsman_admin_username:
opsman_admin_password:

# required network config
singleton_jobs_az:
other_azs:
network_name:
services_network_name:

# internal tile identifiers
product_name: crunchy-postgresql
product_identifier: crunchy-postgresql
product_version: ^03\..*$

# crunchy global properties
properties_consul_server_vm_type: t2.micro
properties_consul_server_disk_type: 1024
properties_postgresql_haproxy_vm_type: t2.micro
properties_postgresql_haproxy_disk_type: 1024
properties_smoke_tests_vm_type: t2.micro
properties_smoke_tests_disk_type: 1024
properties_az_multi_select:   # comma separate list of AZs from cloud config

# crunchy small plan properties
properties_small_vm_type: t2.micro
properties_small_disk_type: 5120
properties_small_postgresql_instance_count: 2
properties_small_postgresql_service_quota: 10

# crunchy medium plan properties
properties_medium_vm_type: t2.micro
properties_medium_disk_type: 30720
properties_medium_postgresql_instance_count: 3
properties_medium_postgresql_service_quota: 10

# crunchy large plan properties
properties_large_vm_type: t2.micro
properties_large_disk_type: 102400
properties_large_postgresql_instance_count: 3
properties_large_postgresql_service_quota: 10

# crunchy extra large plan properties
properties_extra_large_vm_type: t2.micro
properties_extra_large_disk_type: 1048576
properties_extra_large_postgresql_instance_count: 3 
properties_extra_large_postgresql_service_quota: 10






