---

platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

params:
  PRODUCT_NAME:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  SINGLETON_JOBS_AZ:
  OTHER_AZS:
  NETWORK_NAME:
  BACKUP_OPTIONS:
  BACKUP_OPTIONS_CRON_SCHEDULE:
  BACKUP_OPTIONS_BACKUP_ALL_MASTERS:
  BACKUPS:
  BACKUPS_S3_ENDPOINT_URL:
  BACKUPS_S3_BUCKET_NAME:
  BACKUPS_S3_BUCKET_PATH:
  BACKUPS_S3_ACCESS_KEY_ID:
  BACKUPS_S3_SECRET_ACCESS_KEY:
  BACKUPS_S3_REGION:
  BACKUPS_AZURE_STORAGE_ACCOUNT:
  BACKUPS_AZURE_STORAGE_ACCESS_KEY:
  BACKUP_OPTIONS_BACKUP_ALL_MASTERS:
  BACKUPS_AZURE_CONTAINER:
  BACKUPS_AZURE_CONTAINER_PATH:
  BACKUPS_AZURE_BASE_URL:
  BACKUPS_GCS_SERVICE_ACCOUNT_JSON:
  BACKUPS_GCS_PROJECT_ID:
  BACKUPS_GCS_BUCKET_NAME:
  BACKUPS_SCP_USER:
  BACKUPS_SCP_SERVER:
  BACKUPS_SCP_DESTINATION:
  BACKUPS_SCP_SCP_KEY:
  BACKUPS_SCP_PORT:
  PLAN_COLLECTION_NAME:
  PLAN_COLLECTION_DESCRIPTION:
  PLAN_COLLECTION_MAX_STORAGE_MB:
  PLAN_COLLECTION_MAX_USER_CONNECTIONS:
  PLAN_COLLECTION_PRIVATE:
  OPTIONAL_PROTECTIONS:
  OPTIONAL_PROTECTIONS_RECIPIENT_EMAIL:
  OPTIONAL_PROTECTIONS_PREVENT_AUTO_REJOIN:
  OPTIONAL_PROTECTIONS_REPLICATION_CANARY:
  OPTIONAL_PROTECTIONS_NOTIFY_ONLY:
  OPTIONAL_PROTECTIONS_CANARY_POLL_FREQUENCY:
  OPTIONAL_PROTECTIONS_CANARY_WRITE_READ_DELAY:
  INNODB_FLUSH_LOG_AT_TRX_COMMIT:
  SERVER_ACTIVITY_LOGGING:
  AUDIT_LOGGING_EVENTS:
  SERVER_AUDIT_EXCLUDED_USERS_CSV:
  SYSLOG:
  SYSLOG_ADDRESS:
  SYSLOG_PORT:
  BUFFER_POOL_SIZE:
  BUFFER_POOL_SIZE_PERCENT:
  BUFFER_POOL_SIZE_BYTES:
  MYSQL_ROADMIN_PASSWORD:
  MYSQL_SKIP_NAME_RESOLVE:
  MYSQL_INNODB_LARGE_PREFIX_ENABLED:
  MYSQL_MYSQL_START_TIMEOUT:
  MYSQL_METRICS_POLLING_FREQUENCY:
  MYSQL_CLUSTER_PROBE_TIMEOUT:
  MYSQL_TMP_TABLE_SIZE:
  MYSQL_TABLE_OPEN_CACHE:
  MYSQL_TABLE_DEFINITION_CACHE:
  MYSQL_MAX_CONNECTIONS:
  MYSQL_BINLOG_EXPIRE_DAYS:
  MYSQL_CLUSTER_NAME:
  MYSQL_INNODB_STRICT_MODE:
  MYSQL_CLI_HISTORY:
  MYSQL_ALLOW_REMOTE_ADMIN_ACCESS:
  MYSQL_ALLOW_LOCAL_INFILE:
  PROXY_STATIC_IPS:
  PROXY_SHUTDOWN_DELAY:
  PROXY_STARTUP_DELAY:
  CF_MYSQL_BROKER_QUOTA_ENFORCER_PAUSE:
  CF_MYSQL_BROKER_ALLOW_TABLE_LOCKS:
  CF_MYSQL_BROKER_BIND_HOSTNAME:
  MYSQL_SERVER_INSTANCE_TYPE:
  MYSQL_SERVER_INSTANCES:
  MYSQL_PERSISTENT_DISK_MB:
  BACKUP_PREPARE_INSTANCE_TYPE:
  BACKUP_PREPARE_INSTANCES:
  BACKUP_PREPARE_PERSISTENT_DISK_MB:
  MYSQL_PROXY_INSTANCE_TYPE:
  MYSQL_PROXY_INSTANCES:
  MONITORING_INSTANCE_TYPE:
  MONITORING_INSTANCES:
  MYSQL_BROKER_INSTANCE_TYPE:
  MYSQL_BROKER_INSTANCES:

inputs:
  - name: pipelines-repo
  - name: om-cli
  - name: jq

run:
  path: pipelines-repo/tasks/config-mysql/task.sh
