# legacy pivnet token for downloading tile
pivnet_token:

# opsman connection info
opsman_domain_or_ip_address:
opsman_admin_username:
opsman_admin_password:

# required network config
singleton_jobs_az:
other_azs:
network_name:
services_network_name:

# internal tile identifiers
product_name: pivotal-rabbitmq-service
product_identifier: p-rabbitmq
product_version: ^1\.11\..*$

ops_mgr_generate_ssl_endpoint: /api/v0/certificates/generate

metrics_polling_interval: 30 # min: 10
syslog_selector: disabled # (enabled|disabled)
syslog_selector_address:
syslog_selector_port:
syslog_selector_syslog_transport: tcp # (tcp|udp|relp)
syslog_selector_syslog_format: rfc5424 # (rfc5424|job_index_id)
syslog_selector_syslog_tls: false # (true|false)
syslog_selector_syslog_permitted_peer:
syslog_selector_syslog_ca_cert:
on_demand_broker_vm_extensions:
on_demand_broker_plan_1_cf_service_access: "disable" #(enable|disable|manual)
on_demand_broker_plan_1_name: "single-node"
on_demand_broker_plan_1_description: "This plan provides a single dedicated RabbitMQ node"
on_demand_broker_plan_1_instance_quota: 20
on_demand_broker_plan_1_features: "RabbitMQ"
on_demand_broker_plan_1_rabbitmq_az_placement:
on_demand_broker_plan_1_rabbitmq_vm_type:
on_demand_broker_plan_1_rabbitmq_persistent_disk_type:
on_demand_broker_plan_1_rabbitmq_number_of_nodes: 1
on_demand_broker_plan_1_rabbitmq_cluster_partitioning_handling_strategy: "pause_minority" #(pause_minority|autoheal)
on_demand_broker_plan_1_disk_limit_acknowledgement: "non-existant-value" #(acknowledge|non-existant-value)
on_demand_broker_plan_2_selector: "disabled" #(enabled|disabled)
on_demand_broker_plan_2_selector_cf_service_access: "enable" #(enable|disable)
on_demand_broker_plan_2_selector_name: "cluster"
on_demand_broker_plan_2_selector_description: "This plan provides a preconfigured dedicated cluster of RabbitMQ nodes"
on_demand_broker_plan_2_selector_features: "RabbitMQ"
on_demand_broker_plan_2_selector_instance_quota: 0
on_demand_broker_plan_2_selector_rabbitmq_persistent_disk_type:
on_demand_broker_plan_2_selector_rabbitmq_number_of_nodes: 3
on_demand_broker_plan_2_selector_rabbitmq_cluster_partition_handling_strategy: "pause_minority" #(pause_minority|autoheal)
on_demand_broker_plan_2_selector_rabbitmq_az_placement:
on_demand_broker_plan_2_selector_rabbitmq_vm_type:
on_demand_broker_plan_2_selector_disk_limit_acknowledgement: "non-existant-value" #(acknowledge|non-existant-value)
on_demand_broker_plan_3_selector: "disabled" #(enabled|disabled)
on_demand_broker_plan_3_selector_cf_service_access: "enable" #(enable|disable)
on_demand_broker_plan_3_selector_name:
on_demand_broker_plan_3_selector_description:
on_demand_broker_plan_3_selector_features: "RabbitMQ"
on_demand_broker_plan_3_selector_instance_quota: 0
on_demand_broker_plan_3_selector_rabbitmq_persistent_disk_type:
on_demand_broker_plan_3_selector_rabbitmq_number_of_nodes: 3
on_demand_broker_plan_3_selector_rabbitmq_cluster_partition_handling_strategy: "pause_minority" #(pause_minority|autoheal)
on_demand_broker_plan_3_selector_rabbitmq_az_placement:
on_demand_broker_plan_3_selector_rabbitmq_vm_type:
on_demand_broker_plan_3_selector_disk_limit_acknowledgement: "non-existant-value" #(acknowledge|non-existant-value)
on_demand_broker_plan_4_selector: "disabled" #(enabled|disabled)
on_demand_broker_plan_4_selector_cf_service_access: "enable" #(enable|disable)
on_demand_broker_plan_4_selector_name:
on_demand_broker_plan_4_selector_description:
on_demand_broker_plan_4_selector_features: "RabbitMQ"
on_demand_broker_plan_4_selector_instance_quota: 0
on_demand_broker_plan_4_selector_rabbitmq_persistent_disk_type:
on_demand_broker_plan_4_selector_rabbitmq_number_of_nodes: 3
on_demand_broker_plan_4_selector_rabbitmq_cluster_partition_handling_strategy: "pause_minority" #(pause_minority|aut
on_demand_broker_plan_4_selector_rabbitmq_az_placement:
on_demand_broker_plan_4_selector_rabbitmq_vm_type:
on_demand_broker_plan_4_selector_disk_limit_acknowledgement: "non-existant-value" #(acknowledge|non-existant-value)
on_demand_broker_plan_5_selector: "disabled" #(enabled|disabled)
on_demand_broker_plan_5_selector_cf_service_access: "enable" #(enable|disable)
on_demand_broker_plan_5_selector_name:
on_demand_broker_plan_5_selector_description:
on_demand_broker_plan_5_selector_features: "RabbitMQ"
on_demand_broker_plan_5_selector_instance_quota: 0
on_demand_broker_plan_5_selector_rabbitmq_persistent_disk_type:
on_demand_broker_plan_5_selector_rabbitmq_number_of_nodes: 3
on_demand_broker_plan_5_selector_rabbitmq_cluster_partition_handling_strategy: "pause_minority" #(pause_minority|aut
on_demand_broker_plan_5_selector_rabbitmq_az_placement:
on_demand_broker_plan_5_selector_rabbitmq_vm_type:
on_demand_broker_plan_5_selector_disk_limit_acknowledgement: "non-existant-value" #(acknowledge|non-existant-value)
disk_alarm_threshold: # (fixed_50_mb|mem_relative_1_0|mem_relative_1_5|mem_relative_2_0)
server_admin_username:
server_admin_password:
rabbitmq_server_plugins: "rabbitmq_amqp1_0,rabbitmq_auth_backend_ldap,rabbitmq_auth_mechanism_ssl,rabbitmq_consistent_hash_exchange,rabbitmq_federation,rabbitmq_federation_management,rabbitmq_management,rabbitmq_management_visualiser,rabbitmq_mqtt,rabbitmq_shovel,rabbitmq_shovel_management,rabbitmq_stomp,rabbitmq_tracing,rabbitmq_web_stomp,rabbitmq_web_stomp_examples,rabbitmq_event_exchange,rabbitmq_jms_topic_exchange"
ssl_cert_pem:
ssl_private_key_pem:
ssl_cacert:
ssl_verify: false # (true|false)
ssl_verification_depth: 5
ssl_fail_if_no_peer_cert: false # (true|false)
rabbitmq_server_cookie:
rabbitmq_server_config:
ssl_versions: tlsv1.1,tlsv1.2 # (tlsv1.0,tlsv1.1,tlsv1.2)
cluster_partition_handling: pause_minority #(pause_minority|autoheal)
rabbitmq_server_ports: "15672, 5672, 5671, 1883, 8883, 61613, 61614, 15674"
rabbitmq_server_static_ips:
rabbitmq_haproxy_static_ips:
rabbitmq_broker_dns_host:
operator_set_policy_enabled: false # (true|false)
policy_definition:
global_service_instance_quota: 20

rmq_server_instance_type: automatic
rmq_server_instances: 3
rmq_server_node_persistent_disk_size: 30720
rmq_haproxy_instance_type: automatic
rmq_haproxy_instances: 1
rmq_broker_instance_type: automatic
rmq_broker_instances: 1 # (0|1)
rmq_ondemand_instance_type: automatic
rmq_ondemand_instances: 1 # (0|1)
rmq_ondemand_persistent_disk_size: 1024
