---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfnorm/rootfs

params:
  PRODUCT_IDENTIFIER:
  OPSMAN_DOMAIN_OR_IP_ADDRESS:
  OPSMAN_USERNAME:
  OPSMAN_PASSWORD:
  OPS_MGR_GENERATE_SSL_ENDPOINT:
  SINGLETON_JOBS_AZ:
  OTHER_AZS:
  NETWORK_NAME:
  SERVICES_NETWORK_NAME:
  METRICS_POLLING_INTERVAL:
  SYSLOG_SELECTOR:
  SYSLOG_SELECTOR_ADDRESS:
  SYSLOG_SELECTOR_PORT:
  SYSLOG_SELECTOR_SYSLOG_TRANSPORT:
  SYSLOG_SELECTOR_SYSLOG_FORMAT:
  SYSLOG_SELECTOR_SYSLOG_TLS:
  SYSLOG_SELECTOR_SYSLOG_PERMITTED_PEER:
  SYSLOG_SELECTOR_SYSLOG_CA_CERT:
  ON_DEMAND_BROKER_VM_EXTENSIONS:
  ON_DEMAND_BROKER_PLAN_1_CF_SERVICE_ACCESS:
  ON_DEMAND_BROKER_PLAN_1_NAME:
  ON_DEMAND_BROKER_PLAN_1_DESCRIPTION:
  ON_DEMAND_BROKER_PLAN_1_INSTANCE_QUOTA:
  ON_DEMAND_BROKER_PLAN_1_FEATURES:
  ON_DEMAND_BROKER_PLAN_1_RABBITMQ_AZ_PLACEMENT:
  ON_DEMAND_BROKER_PLAN_1_RABBITMQ_VM_TYPE:
  ON_DEMAND_BROKER_PLAN_1_RABBITMQ_PERSISTENT_DISK_TYPE:
  ON_DEMAND_BROKER_PLAN_1_DISK_LIMIT_ACKNOWLEDGEMENT:
  ON_DEMAND_BROKER_PLAN_2_SELECTOR:
  ON_DEMAND_BROKER_PLAN_2_SELECTOR_CF_SERVICE_ACCESS:
  ON_DEMAND_BROKER_PLAN_2_SELECTOR_NAME:
  ON_DEMAND_BROKER_PLAN_2_SELECTOR_DESCRIPTION:
  ON_DEMAND_BROKER_PLAN_2_SELECTOR_FEATURES:
  ON_DEMAND_BROKER_PLAN_2_SELECTOR_INSTANCE_QUOTA:
  ON_DEMAND_BROKER_PLAN_2_SELECTOR_RABBITMQ_PERSISTENT_DISK_TYPE:
  ON_DEMAND_BROKER_PLAN_2_SELECTOR_RABBITMQ_NUMBER_OF_NODES:
  ON_DEMAND_BROKER_PLAN_2_SELECTOR_RABBITMQ_CLUSTER_PARTITION_HANDLING_STRATEGY:
  ON_DEMAND_BROKER_PLAN_2_SELECTOR_RABBITMQ_AZ_PLACEMENT:
  ON_DEMAND_BROKER_PLAN_2_SELECTOR_RABBITMQ_VM_TYPE:
  ON_DEMAND_BROKER_PLAN_2_SELECTOR_DISK_LIMIT_ACKNOWLEDGEMENT:
  ON_DEMAND_BROKER_PLAN_3_SELECTOR:
  ON_DEMAND_BROKER_PLAN_3_SELECTOR_CF_SERVICE_ACCESS:
  ON_DEMAND_BROKER_PLAN_3_SELECTOR_NAME:
  ON_DEMAND_BROKER_PLAN_3_SELECTOR_DESCRIPTION:
  ON_DEMAND_BROKER_PLAN_3_SELECTOR_FEATURES:
  ON_DEMAND_BROKER_PLAN_3_SELECTOR_INSTANCE_QUOTA:
  ON_DEMAND_BROKER_PLAN_3_SELECTOR_RABBITMQ_PERSISTENT_DISK_TYPE:
  ON_DEMAND_BROKER_PLAN_3_SELECTOR_RABBITMQ_NUMBER_OF_NODES:
  ON_DEMAND_BROKER_PLAN_3_SELECTOR_RABBITMQ_CLUSTER_PARTITION_HANDLING_STRATEGY:
  ON_DEMAND_BROKER_PLAN_3_SELECTOR_RABBITMQ_AZ_PLACEMENT:
  ON_DEMAND_BROKER_PLAN_3_SELECTOR_RABBITMQ_VM_TYPE:
  ON_DEMAND_BROKER_PLAN_3_SELECTOR_DISK_LIMIT_ACKNOWLEDGEMENT:
  ON_DEMAND_BROKER_PLAN_4_SELECTOR:
  ON_DEMAND_BROKER_PLAN_4_SELECTOR_CF_SERVICE_ACCESS:
  ON_DEMAND_BROKER_PLAN_4_SELECTOR_NAME:
  ON_DEMAND_BROKER_PLAN_4_SELECTOR_DESCRIPTION:
  ON_DEMAND_BROKER_PLAN_4_SELECTOR_FEATURES:
  ON_DEMAND_BROKER_PLAN_4_SELECTOR_INSTANCE_QUOTA:
  ON_DEMAND_BROKER_PLAN_4_SELECTOR_RABBITMQ_PERSISTENT_DISK_TYPE:
  ON_DEMAND_BROKER_PLAN_4_SELECTOR_RABBITMQ_NUMBER_OF_NODES:
  ON_DEMAND_BROKER_PLAN_4_SELECTOR_RABBITMQ_CLUSTER_PARTITION_HANDLING_STRATEGY:
  ON_DEMAND_BROKER_PLAN_4_SELECTOR_RABBITMQ_AZ_PLACEMENT:
  ON_DEMAND_BROKER_PLAN_4_SELECTOR_RABBITMQ_VM_TYPE:
  ON_DEMAND_BROKER_PLAN_4_SELECTOR_DISK_LIMIT_ACKNOWLEDGEMENT:
  ON_DEMAND_BROKER_PLAN_5_SELECTOR:
  ON_DEMAND_BROKER_PLAN_5_SELECTOR_CF_SERVICE_ACCESS:
  ON_DEMAND_BROKER_PLAN_5_SELECTOR_NAME:
  ON_DEMAND_BROKER_PLAN_5_SELECTOR_DESCRIPTION:
  ON_DEMAND_BROKER_PLAN_5_SELECTOR_FEATURES:
  ON_DEMAND_BROKER_PLAN_5_SELECTOR_INSTANCE_QUOTA:
  ON_DEMAND_BROKER_PLAN_5_SELECTOR_RABBITMQ_PERSISTENT_DISK_TYPE:
  ON_DEMAND_BROKER_PLAN_5_SELECTOR_RABBITMQ_NUMBER_OF_NODES:
  ON_DEMAND_BROKER_PLAN_5_SELECTOR_RABBITMQ_CLUSTER_PARTITION_HANDLING_STRATEGY:
  ON_DEMAND_BROKER_PLAN_5_SELECTOR_RABBITMQ_AZ_PLACEMENT:
  ON_DEMAND_BROKER_PLAN_5_SELECTOR_RABBITMQ_VM_TYPE:
  ON_DEMAND_BROKER_PLAN_5_SELECTOR_DISK_LIMIT_ACKNOWLEDGEMENT:
  DISK_ALARM_THRESHOLD:
  SERVER_ADMIN_USERNAME:
  SERVER_ADMIN_PASSWORD:
  RABBITMQ_SERVER_PLUGINS:
  SSL_CERT_PEM:
  SSL_PRIVATE_KEY_PEM:
  SSL_CACERT:
  SSL_VERIFY:
  SSL_VERIFICATION_DEPTH:
  SSL_FAIL_IF_NO_PEER_CERT:
  RABBITMQ_SERVER_COOKIE:
  RABBITMQ_SERVER_CONFIG:
  SSL_VERSIONS:
  CLUSTER_PARTITION_HANDLING:
  RABBITMQ_SERVER_PORTS:
  RABBITMQ_SERVER_STATIC_IPS:
  RABBITMQ_HAPROXY_STATIC_IPS:
  RABBITMQ_BROKER_DNS_HOST:
  OPERATOR_SET_POLICY_ENABLED:
  POLICY_DEFINITION:
  GLOBAL_SERVICE_INSTANCE_QUOTA:
  RMQ_SERVER_INSTANCE_TYPE:
  RMQ_SERVER_INSTANCES:
  RMQ_SERVER_NODE_PERSISTENT_DISK_SIZE:
  RMQ_HAPROXY_INSTANCE_TYPE:
  RMQ_HAPROXY_INSTANCES:
  RMQ_BROKER_INSTANCE_TYPE:
  RMQ_BROKER_INSTANCES:
  RMQ_ONDEMAND_INSTANCE_TYPE:
  RMQ_ONDEMAND_INSTANCES:
  RMQ_ONDEMAND_PERSISTENT_DISK_SIZE:

inputs:
  - name: pcf-pipelines-tileinstalls

run:
  path: pcf-pipelines-tileinstalls/tasks/config-rabbitmq/task.sh
